"""Add visitor tracking table

Revision ID: 844685d729fb
Revises: 0eabed5fb245
Create Date: 2026-03-08 20:54:48.900479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844685d729fb'
down_revision = '0eabed5fb245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('page_visited', sa.String(length=255), nullable=False),
    sa.Column('first_visit', sa.DateTime(), nullable=False),
    sa.Column('last_visit', sa.DateTime(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitors_ip_address'), ['ip_address'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_ip_address'))

    op.drop_table('visitors')
    # ### end Alembic commands ###
